insert into companyData (companyName,managerId) values('ABOBE',2);
insert into companyData (companyName,managerId) values('ACCENTURE',2);
insert into companyData (companyName,managerId) values('ALSTOM',2);
insert into companyData (companyName,managerId) values('AMADEUS LABS',2);
insert into companyData (companyName,managerId) values('AMAZON',2);
insert into companyData (companyName,managerId) values('APPVIEWX',2);
insert into companyData (companyName,managerId) values('ARCADIA',2);
insert into companyData (companyName,managerId) values('ARISTA',2);
insert into companyData (companyName,managerId) values('ATLASSIAN',2);
insert into companyData (companyName,managerId) values('BNP PARIBAS',2);
insert into companyData (companyName,managerId) values('BNP PARIBAS ISPL',2);
insert into companyData (companyName,managerId) values('BNY MELLON',2);
insert into companyData (companyName,managerId) values('BOSCH',2);
insert into companyData (companyName,managerId) values('CAMS(COMPUTER AGE MANAGEMENT SEVICES)',2);
insert into companyData (companyName,managerId) values('CAPEGEMINI',2);
insert into companyData (companyName,managerId) values('CATERPILLAR',2);
insert into companyData (companyName,managerId) values('CERNER',2);
insert into companyData (companyName,managerId) values('CHARGEBEE',2);
insert into companyData (companyName,managerId) values('CISCO',2);
insert into companyData (companyName,managerId) values('COGNIZANT',2);
insert into companyData (companyName,managerId) values('COMVIVA',2);
insert into companyData (companyName,managerId) values('DATAFOUNDRY.AI',2);
insert into companyData (companyName,managerId) values('E2OPEN',2);
insert into companyData (companyName,managerId) values('EPIKINDIFI',2);
insert into companyData (companyName,managerId) values('EY',2);
insert into companyData (companyName,managerId) values('FIDILITY',2);
insert into companyData (companyName,managerId) values('FRACTAL ANALYSIS',2);
insert into companyData (companyName,managerId) values('GE',2);
insert into companyData (companyName,managerId) values('GENPACT',2);
insert into companyData (companyName,managerId) values('HASHED IN',2);
insert into companyData (companyName,managerId) values('HONEYWELL',2);
insert into companyData (companyName,managerId) values('HYPERVERGE',2);
insert into companyData (companyName,managerId) values('IBM',2);
insert into companyData (companyName,managerId) values('INCREFF',2);
insert into companyData (companyName,managerId) values('INFOSYS',2);
insert into companyData (companyName,managerId) values('INTUIT',2);
insert into companyData (companyName,managerId) values('KLA TENCOR',2);
insert into companyData (companyName,managerId) values('KPMG',2);
insert into companyData (companyName,managerId) values('L&T',2);
insert into companyData (companyName,managerId) values('LATENT VIEW ANALYTICS',2);
insert into companyData (companyName,managerId) values('LISTER TECHNOLOGIES',2);
insert into companyData (companyName,managerId) values('MCKINSEY',2);
insert into companyData (companyName,managerId) values('MERCEDES BENZ',2);
insert into companyData (companyName,managerId) values('MICRO FOCUS',2);
insert into companyData (companyName,managerId) values('MICROCHIP',2);
insert into companyData (companyName,managerId) values('MICROSOFT',2);
insert into companyData (companyName,managerId) values('NIELSENIQ',2);
insert into companyData (companyName,managerId) values('NOKIA',2);
insert into companyData (companyName,managerId) values('NPCI',2);
insert into companyData (companyName,managerId) values('OPTUM',2);
insert into companyData (companyName,managerId) values('ORACLE',2);
insert into companyData (companyName,managerId) values('PAY U',2);
insert into companyData (companyName,managerId) values('PROVIDENCE',2);
insert into companyData (companyName,managerId) values('PWC',2);
insert into companyData (companyName,managerId) values('RAZOR PAY',2);
insert into companyData (companyName,managerId) values('ROBERT BOSCH',2);
insert into companyData (companyName,managerId) values('ROOT QUOTIENT',2);
insert into companyData (companyName,managerId) values('SAHAJ',2);
insert into companyData (companyName,managerId) values('SAMSUNG ELECTRO-MECHANICS',2);
insert into companyData (companyName,managerId) values('SAP LABS',2);
insert into companyData (companyName,managerId) values('SCHLUMBERGER',2);
insert into companyData (companyName,managerId) values('SCHNEIDER ELECTRIC',2);
insert into companyData (companyName,managerId) values('SIGNIFY INNOVATION LABS',2);
insert into companyData (companyName,managerId) values('SS&C EZE',2);
insert into companyData (companyName,managerId) values('TALLY SOLUTIONS',2);
insert into companyData (companyName,managerId) values('TARGET',2);
insert into companyData (companyName,managerId) values('TATA COMMUNICATIONS',2);
insert into companyData (companyName,managerId) values('TCS',2);
insert into companyData (companyName,managerId) values('THE MATH COMPANY',2);
insert into companyData (companyName,managerId) values('TIGER ANALYTICS',2);
insert into companyData (companyName,managerId) values('TOSHIBA',2);
insert into companyData (companyName,managerId) values('TREDENCE ANALYTICS',2);
insert into companyData (companyName,managerId) values('TRIANZ',2);
insert into companyData (companyName,managerId) values('VALEO',2);
insert into companyData (companyName,managerId) values('VANENBURG',2);
insert into companyData (companyName,managerId) values('VERIZON',2);
insert into companyData (companyName,managerId) values('VERSA NETWORKS',2);
insert into companyData (companyName,managerId) values('VISTEON CORPORATION',2);
insert into companyData (companyName,managerId) values('VM WARE',2);
insert into companyData (companyName,managerId) values('VOLVO',2);
insert into companyData (companyName,managerId) values('WIPRO',2);
insert into companyData (companyName,managerId) values('WONKSKNOW TECHNOLOGIES',2);
insert into companyData (companyName,managerId) values('ZOOM RX',2);
insert into companyData (companyName,managerId) values('ZSCALER',2);
insert into companyData (companyName,managerId) values('[24]7.AI',2);
