insert into companyData (companyName,createdAt,managerEmail) values('CISCO ','2021-08-07','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('INTUIT','2021-08-07','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ROOT QUOTIENT','2021-12-07','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ARISTA','2021-12-08','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('SAHAJ','2021-12-09','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('EPIKINDIFI','2021-12-10','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('PROVIDENCE GLOBAL','2021-12-11','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('NIELSENIQ','2021-12-12','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('INCREFF','2021-12-13','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('MCKINSEY','2021-12-14','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('APPVIEWX ','2021-12-15','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('FIDILITY ','2021-12-16','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('SAP LABS','2021-12-17','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('MICROSOFT','2021-12-18','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('TALLY SOLUTIONS','2021-12-19','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('INFOSYS','2021-12-20','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('EY INDIA','2021-12-21','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ORACLE','2021-08-07','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('VERSA NETWORKS','2021-08-08','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('AMAZON','2021-08-09','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('IBM','2021-08-10','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('KLA TENCOR','2021-08-11','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('WONKSKNOW TECHNOLOGIES','2021-08-12','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('HYPERVERGE','2021-08-13','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('FRACTAL ANALYSIS','2021-08-14','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('RAZOR PAY','2021-08-15','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('VM WARE','2021-08-16','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('PWC','2021-08-17','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ZOOM RX','2021-08-18','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('CATTERPILLAR','2021-08-19','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('TCS-DIGITAL','2021-08-20','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('TCS-NINJA','2021-08-21','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ATLASSIAN','2021-08-22','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ROBERT BOSCH','2021-08-23','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('[24]7.AI','2021-08-24','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('HASHED IN','2021-08-25','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('COGNIZANT-GENC NEXT','2021-08-26','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('COGNIZANT-GENC ELEVATE ','2021-08-27','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('COGNIZANT-GENC','2021-08-28','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('PAY U','2021-08-29','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ALSTOM','2021-08-30','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('VANENBURG','2021-08-31','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('VERIZON','2021-09-01','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('THE MATH COMPANY','2021-09-02','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('LISTER TECHNOLOGIES','2021-09-03','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('MERCEDES BENZ- TRUCK','2021-09-04','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('MERECEDES BENZ-CARS','2021-09-05','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('CHARGEBEE','2021-09-06','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('OPTUM','2021-09-07','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('MICRO FOCUS','2021-09-08','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('SS&C EZE','2021-09-09','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('ZSCALER','2021-09-10','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('TIGER ANALYTICS','2021-09-11','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('DATAFOUNDRY.AI','2021-09-12','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('CAPEGEMINI','2021-09-13','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('WIPRO','2021-09-14','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('SCHNEIDER ELECTRIC','2021-09-15','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('KPMG','2021-09-16','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('TARGET ','2021-09-17','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('L&T Technology services','2021-09-18','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('Toshiba','2021-09-19','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('CERNER','2021-09-20','goxtham@gmail.com');
insert into companyData (companyName,createdAt,managerEmail) values('NPCI','2021-09-21','goxtham@gmail.com');
