INSERT INTO company (companyName) VALUES ('CISCO');
INSERT INTO company (companyName) VALUES ('INTUIT');
INSERT INTO company (companyName) VALUES ('ROOT QUOTIENT');
INSERT INTO company (companyName) VALUES ('ARISTA');
INSERT INTO company (companyName) VALUES ('SAHAJ');
INSERT INTO company (companyName) VALUES ('EPIKINDIFI');
INSERT INTO company (companyName) VALUES ('PROVIDENCE GLOBAL');
INSERT INTO company (companyName) VALUES ('NIELSENIQ');
INSERT INTO company (companyName) VALUES ('INCREFF');
INSERT INTO company (companyName) VALUES ('MCKINSEY');
INSERT INTO company (companyName) VALUES ('APPVIEWX');
INSERT INTO company (companyName) VALUES ('FIDILTY');
INSERT INTO company (companyName) VALUES ('SAP LABS');
INSERT INTO company (companyName) VALUES ('MICROSOFT');
INSERT INTO company (companyName) VALUES ('TALLY SOLUTIONS');
INSERT INTO company (companyName) VALUES ('INFOSYS');
INSERT INTO company (companyName) VALUES ('EY INDIA');
INSERT INTO company (companyName) VALUES ('ORACLE');
INSERT INTO company (companyName) VALUES ('VERSA NETWORKS');
INSERT INTO company (companyName) VALUES ('AMAZON');
INSERT INTO company (companyName) VALUES ('IBM');
INSERT INTO company (companyName) VALUES ('KLA TENCOR');
INSERT INTO company (companyName) VALUES ('WONKSKNOW TECHNOLOGIES');
INSERT INTO company (companyName) VALUES ('HYPERVERGE');
INSERT INTO company (companyName) VALUES ('FRACTAL ANALYSIS');
INSERT INTO company (companyName) VALUES ('RAZOR PAY');
INSERT INTO company (companyName) VALUES ('VM WARE');
INSERT INTO company (companyName) VALUES ('PWC');
INSERT INTO company (companyName) VALUES ('ZOOM RX');
INSERT INTO company (companyName) VALUES ('CATTERPILLAR');
INSERT INTO company (companyName) VALUES ('TCS');
INSERT INTO company (companyName) VALUES ('ATLASSIAN');
INSERT INTO company (companyName) VALUES ('ROBERT BOSCH');
INSERT INTO company (companyName) VALUES ('[24]7.AI');
INSERT INTO company (companyName) VALUES ('HASHED IN');
INSERT INTO company (companyName) VALUES ('COGNIZANT-GENC');
INSERT INTO company (companyName) VALUES ('PAY U');
INSERT INTO company (companyName) VALUES ('ALSTOM');
INSERT INTO company (companyName) VALUES ('VANENBURG');
INSERT INTO company (companyName) VALUES ('VERIZON');
INSERT INTO company (companyName) VALUES ('THE MATH COMPANY');
INSERT INTO company (companyName) VALUES ('LISTER TECHNOLOGIES');
INSERT INTO company (companyName) VALUES ('MERCEDES BENZ');
INSERT INTO company (companyName) VALUES ('CHARGEBEE');
INSERT INTO company (companyName) VALUES ('OPTUM');
INSERT INTO company (companyName) VALUES ('MICRO FOCUS');
INSERT INTO company (companyName) VALUES ('SS&C EZE');
INSERT INTO company (companyName) VALUES ('ZSCALER');
INSERT INTO company (companyName) VALUES ('TIGER ANALYTICS');
INSERT INTO company (companyName) VALUES ('DATAFOUNDRY.AI');
INSERT INTO company (companyName) VALUES ('CAPEGEMINI');
INSERT INTO company (companyName) VALUES ('WIPRO');
INSERT INTO company (companyName) VALUES ('SCHNEIDER ELECTRIC');
INSERT INTO company (companyName) VALUES ('KPMG');
INSERT INTO company (companyName) VALUES ('TARGET');
INSERT INTO company (companyName) VALUES ('L&T Technology services');
INSERT INTO company (companyName) VALUES ('Toshiba');
INSERT INTO company (companyName) VALUES ('CERNER');
INSERT INTO company (companyName) VALUES ('NPCI');