INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18301', 'ABHILASH SASIKUMAR', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18302', 'ACHANTA RAMYA SRI', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18303', 'ADITHI GIRIDHARAN', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18304', 'B AISHWARYA', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18305', 'ANANTHAPADMANABHA.M.', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18306', 'SAI KAMAL', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18307', 'ASHWIN K', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18308', 'VAIBHAV KRISHNA BANDLA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18309', 'BEZAWADA SUDHEER', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18310', 'CHANDRAVADHANA A', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18311', 'SAI PRIYATHAM CHERUKU', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18312', 'CHILAKAPATI VENKATA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18313', 'DHANESH KUMAR A C', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18314', 'DHIVAKAR KARUPPANAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18315', 'DUPPANAPUDI SURYA TEJA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18316', 'D. V. S. DINESH CHANDRA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18317', 'ESAM HARSHA SANKEERTH', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18318', 'ESWAR V', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18319', 'GAYATHRI', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18320', 'N GOKULAKANNAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18321', 'I.GURU PRASANNA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18322', 'HARISH S G', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18323', 'HARIVARDAN M', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18325', 'JANANI R', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18326', 'JAYAVALLABBESH K', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18327', 'JODISS TRIBHU', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18328', 'HEMANTHA SAI SANDHYA', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18329', 'KADIYALA SASIDHAR', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18330', 'KANDE SREEKAR', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18331', 'KARTHIKEYAN R V', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18332', 'B.KIRTHI SAGAR', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18333', 'AKHILA KUMARI KOLLI', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18334', 'K. VISHAL VARMA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18335', 'LEKHAZ SUVVARI', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18336', 'LOKESH KASAMNENI', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18337', 'LOKESHVAR S D', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18338', 'MADALA SAI GHOWTHAM', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18339', 'MIGHIL DATH A', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18340', 'M. SAI VEDA SRINIJA', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18342', 'PRANESH M', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18344', 'RAJENDRA PRASATH S S', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18345', 'R. GOUTHAM', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18346', 'RAMPALLI VENKATA LIKITH', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18347', 'RUDRARAJU DHARMESH', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18348', 'SABARI RAJU S', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18349', 'K B SAI HITHARTH', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18350', 'SALADI DURGA SAI SURYA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18351', 'S. SANCHITHA SRI', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18352', 'SANJITH V', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18353', 'SANKARSHANA. A', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18354', 'SASHANK VISWESHWARAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18355', 'SHAKTHI SARAVANAN.S', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18356', 'SHYAM NAGARAJAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18358', 'SIVA BALAN S', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18359', 'SIVADATTA GUNTURI', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18360', 'S SRIVATHSAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18362', 'TANMAAY KANKARIA', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18363', 'THIRUMARAI SELVAN R.', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18364', 'VEMULA DOWTYA SRI', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18365', 'VIPPALA S S', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18366', 'VISHAKHA RAMASWAMY', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18367', 'S. VISHNU KUMAR', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18368', 'YADHU NANDAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18369', 'RANJIT CHANDRAMOHANAN', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18370', 'VINTHA SAI KUSHAL REDDY', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18371', 'ESWAR M', 'M', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18372', 'THUMMA SATHWIKA', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18373', 'PAMPATI SIDHI SRI', 'F', 'D', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18374', 'SKANDAN S', 'F', 'D', '2022', 'CB', 'CSE', '0');
