INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18101', 'AADHITH S.', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18102', 'ABDUL GOUSE SHAIK', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18104', 'ACHANTA HARISH', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18105', 'ADITHYA P VARMA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18106', 'VENKATA SAI SRIRAM', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18107', 'ANKITHA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18108', 'ARAVIND NP', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18109', 'ARAVINDH S', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18110', 'ASHWITH N.', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18111', 'B. NARASIMHA REDDY', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18112', 'CHEKURI DHANUSH VARMA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18114', 'DHIVYA G', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18115', 'ELAVENIL PUGAZHENDI', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18116', 'GAJULASIRI CHANDANA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18117', 'GARLAPATI LOKESH SIVA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18118', 'V.HAREESH', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18119', 'HARI HARA SUDHAN S', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18120', 'M. HEMCHUDAESH', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18122', 'JOSEPH SUBASH KANICHAI', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18123', 'KAMIREDDY SREEKAR', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18124', 'KARAN T', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18125', 'KARTHIK DESAI', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18126', 'KONJETI SYAM SUKESH', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18128', 'KUNDA DURGA VENKATA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18129', 'LOGESHWARAN R', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18130', 'MEGANANTHAN K', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18131', 'MRITYUNJAYA P V', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18132', 'MUKESH M M', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18134', 'N. S. SUSHANK', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18135', 'S.NAGULAN', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18136', 'PAMISETTY PRUTHVE REJ', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18137', 'N. PAVAN KRUTHIK', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18138', 'PEMMASANI UPENDRA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18139', 'PENUMATSA SASHANK', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18140', 'R. PRANAV AJAY', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18141', 'PRATHISH S', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18142', 'RAJ PRADEEP P', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18143', 'ROOPA VIDHYA G', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18144', 'K SAI SUDHAMSH', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18146', 'SAINATH CHANDRASEKAR', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18147', 'SANJHEEVI. S. V.', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18148', 'SHAIK AWEZ', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18149', 'SHASHANK V BARATWAJ', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18150', 'P SOMNATH', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18151', 'SRINIVASA KRISHNAN A N', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18152', 'SUDARSHANA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18154', 'TADISHETTY DHARMARAJ', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18155', 'M. TEJASWINI ANUHYA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18156', 'THUKKARAM S', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18157', 'VADDI SAI VARSHITHA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18158', 'VAITLA LAKSHMI ROSHINI', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18159', 'VANDANA SAIDEV', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18160', 'VEJJU SAI VENKATA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18161', 'VENDOTI SUREKHA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18162', 'VENKATARAMAN', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18163', 'VIGNESH. H', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18164', 'VIGNESH KUMAR S', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18165', 'VISHAAL KARTHIK M', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18166', 'VISHAAL SHIVA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18167', 'VISHNU S NAIR', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18168', 'Y. YASASVI KRISHNA', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18169', 'SURESH J', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18170', 'NAMBURU TEJASWI', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18171', 'DIVYA SHANKAR', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18172', 'KEERTHIKA S', 'F', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18173', 'THARUN KUMAR A', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18174', 'DANGETI HARSHA', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18511', 'GUHAN K', 'M', 'B', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18512', 'SANJEEV D', 'F', 'B', '2022', 'CB', 'CSE', '0');
