INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18001', 'AAKASH KRISHNA R', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18002', 'ABHI SUWETHA', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18003', 'AKULA SUDHAMSHU', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18004', 'ANIRUDH B', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18005', 'ANVITHA YERNENI', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18006', 'SAI PRATEEK ATLURI', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18007', 'AVULA SANDEEP REDDY', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18008', 'BALAJI D', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18009', 'BANDI KISHORE REDDY', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18010', 'BANDI SAI NIKHIL REDDY', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18011', 'SAI MADHAV BIKKINA', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18012', 'CHAVALAM NIKHITHA', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18013', 'CHEEMALAMARRI V S', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18015', 'DEV MITHRAN .J', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18016', 'GANAPATHI', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18017', 'GULLAPUDI ROHITH GUPTA', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18019', 'HARIHARAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18020', 'HARINEE N', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18021', 'HARSHAVARDHINI B', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18022', 'HIRUTHIK J', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18023', 'D. JAGADEESHRAM', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18024', 'J. SAIRAM SAMPATH', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18025', 'G.JANVITHA', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18026', 'JINKA MARUTHI PRASAD', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18027', 'K. SAI PRANAVI', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18028', 'KISHORE SARAVANAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18029', 'KISHORE KUMAR A', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18030', 'KOLISETTY SAI MANOJ', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18031', 'JHANSI LAKSHMI', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18032', 'KOTA ANUDEEP', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18033', 'KOUSIK KUCHIPUDI', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18035', 'KUSAMPUDI PAVAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18036', 'NIDHARSHAN A', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18037', 'NISHITA DASH', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18038', 'NITHEESE T', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18040', 'VLN NITIN VAMSI DANTU', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18041', 'DIVYASRI PARRIPATI', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18042', 'PARVANA J KURUPPAL', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18043', 'PAVITRA B', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18044', 'PRANESH M.', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18045', 'PREETHI P.', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18046', 'RAVILLA BHAVYA', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18047', 'RISHINATH T M', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18048', 'SAI KISHAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18049', 'SAI RAM BANAVATHU', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18052', 'SHYAM SREEVALSAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18053', 'SOWMIYANARAYAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18054', 'SRIDHARAN A.R.', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18056', 'SUDARSH VENKAT J. R.', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18057', 'SUJANPRAKASH P', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18058', 'SURAJ SATHEESAN', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18059', 'SURYA N B', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18060', 'SWETHA', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18061', 'TALLURI TARUN TEJA', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18062', 'VADDI RAVI TEJA', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18063', 'VANUKURI REVANTH', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18064', 'VEMI REDDY ASRITHA', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18065', 'VENKATA SAI RAJARAM', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18066', 'VENKATA TEJDEEP', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18067', 'VIJAYA SAI KARTHIK H', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18068', 'VISHNU SAI VISWAJITH', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18069', 'DHEERAJ VARGHESE', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18070', 'KRISHNA SHASANK V S', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18071', 'MONISHA S', 'F', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18501', 'HARISH K', 'M', 'A', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18502', 'HRIDHI SETHI', 'F', 'A', '2022', 'CB', 'CSE', '0');
