INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18201', 'AADURU VENKATA HEMA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18202', 'S.AAKASH MUTHIAH', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18203', 'ABISHEK VASANTHAN A S', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18204', 'M. S. ADARSH', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18205', 'ADITHI NARAYAN', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18206', 'AMBATI NAGA SREEHARSHA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18207', 'ANAND DEVARAJAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18208', 'ARJUN DEV P.K', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18209', 'J. ARUN KUMAR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18210', 'ARVIND BALAJEE ANANTHA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18211', 'ASHWIN NAIR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18212', 'ASHWIN VENKATESAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18213', 'E. ASWANTH RAGAVENDRA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18214', 'R ASWATH SUNDAR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18217', 'DEEKSHAN S', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18218', 'DHARUN VENKATESH M.', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18219', 'GANESH UMASANKAR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18220', 'GAUTAM PANIGRAHI', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18221', 'GILLELLA SAI SHANTHAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18223', 'GODAVARTHI MANOJ', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18224', 'GORIJALA HEMA', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18225', 'GOWRI SHANKAR B', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18226', 'GRANDHI LAKSHMI YAMINI', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18227', 'GUBBALA SRIRAM', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18228', 'HANCHATE SARAVAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18230', 'KAILAASH B', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18231', 'KARTHIC NARAYANAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18232', 'KRISHNA SANKEERTH', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18233', 'KIRTHIK RAJA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18234', 'K.CHANDRA MOHAN REDDY', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18235', 'KUSHAGRA KUMAR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18236', 'LATHIKA.D', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18237', 'M.MANOJKUMAR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18238', 'MARNENI VENKATA LOKESH', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18239', 'MONISH RAAJ L', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18240', 'HASWANTH RAJESH', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18241', 'NIRANJANA ASHOK', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18242', 'NIRANJANA SUNISH', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18243', 'PONNADA YASWANTHRAM', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18244', 'REDDYBATHUNI MOHAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18245', 'A.T ROHIT SURYA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18246', 'ROSHNI RAJESH', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18247', 'SAI BRAHADEESH B', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18248', 'SAI KIRAN S', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18249', 'SAI RAMANAN M K', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18250', 'A.SAI THARUN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18251', 'V. SANJEEVI', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18252', 'SATYAVADA HEMA SAI TEJA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18253', 'SHAIK MASTANVALI', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18254', 'S.SNEHA LATHA', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18255', 'R. SREE RANJANI', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18256', 'SREHARI T', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18257', 'A. SRI SAKTHI MAHESWARI', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18258', 'M S SUDARSHAN', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18259', 'K. TANYA', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18261', 'TATA SAI SRUTHI', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18262', 'THAANVI SUDARSAN MEDA', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18264', 'TULA SRIRAM KUMAR', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18265', 'AKASH VENKATA', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18266', 'VENKATASUBRAMANIAN N', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18268', 'VIGNESH P S', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18269', 'SHYAM SUNDAR A', 'M', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18270', 'TADIMARRI BHAVANA', 'F', 'C', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18271', 'MARRI MANIKANTA REDDY', 'F', 'C', '2022', 'CB', 'CSE', '0');
