INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18401', 'AADHITYA TEJASWIN P S', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18402', 'AADITYA UMASHANKAR', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18403', 'ABHINAAV MAANAV V', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18404', 'ABISHECK KATHIRVEL', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18405', 'ADAPA CHIRANJEEVI', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18406', 'AISHWARYA S R', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18407', 'TEJA VENKAT AKULA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18408', 'AKUTHOTA KALYAN SAI', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18409', 'APOORVAA S RAGHAVAN', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18410', 'ARVIND T.', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18411', 'BALAJI R', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18413', 'BALUSU MOHAN SRI SIVA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18414', 'BOMMINENI SAHASRA', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18415', 'DHANUSH CHELLAMUTHU', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18416', 'DHANVANTH S', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18417', 'DHARSAN R', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18418', 'PRUDHVI SAI KRISHNA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18419', 'VENKATA KRISHNA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18420', 'GAUTAM KRISHNA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18421', 'G SWATHIKA ', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18423', 'G. YUKTHA REDDY', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18424', 'HARIKRISHNA N', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18425', 'P. HAYMA SUNDER', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18426', 'JEEV S S', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18427', 'KAMBHAM SWAPNIKA', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18428', 'KARVETI LEENA REDDY', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18429', 'KATAMNENI SASI KIRAN', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18430', 'KIRAN KUMAR A.', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18431', 'KOMALA SHASHIDHAR', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18432', 'K.DHANUSH KUMAR', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18433', 'KORAPROLU VENKATA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18434', 'KRISHNA SHARMA S', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18435', 'MADDU JAYA SAI DURGA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18436', 'MAMIDELA ADITYA SAI', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18437', 'MANDRU VINAY', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18438', 'M. HEMANTH SAI REDDY', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18439', 'V. V. MITHUN ROSINTH', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18440', 'C.MONISHVER', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18441', 'PATIBANDLA JYOTHI BHAVANI', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18442', 'POOJA KANNAN', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18443', 'POTTI SHANMUKA ABHINAY', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18444', 'A. RAGHUDATTA VINAY', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18445', 'RAGUL A', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18447', 'RAMANISH SHANKAR S. G.', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18448', 'RAVULA DHANUSH REDDY', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18449', 'NAGA SURYA SATYA SAI', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18450', 'ROHITH RAJESH', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18451', 'SAMYUKTH SURESH SUDHA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18452', 'SANDHYA S', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18453', 'SANJITH RAGUL V', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18454', 'SANJNA SURESH', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18455', 'SASMITHAA V S', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18456', 'SHRI HARI NITHIN K M', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18457', 'S. A. SIVASINI NETRA', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18458', 'S.SREE HARRSHA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18460', 'SURAPARAJU THA SAI', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18461', 'SWARAN KARTHIKEYAN', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18462', 'SAI NITEESH TALASU', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18463', 'THARUN PRASAD S', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18464', 'VELAGAPUDI HEMANTHA', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18465', 'VEMURI MUNI VINEESH', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18466', 'VIDYA R MENON', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18467', 'VIJAY SWAMINATHAN', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18468', 'VISHAL MENON', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18469', 'SIDHARTH R', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18470', 'SINGAM AKSHAYA', 'F', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18471', 'SHRI HARI PRAJAPATI B', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18472', 'MANNAM SAITEJA', 'M', 'E', '2022', 'CB', 'CSE', '0');
INSERT INTO student (rollNo, fullName, gender, section, batch, campus, dept, isHigherStudies) VALUES ('CB.EN.U4CSE18541', 'KARTHICK CHANDRAN G', 'F', 'E', '2022', 'CB', 'CSE', '0');
